apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: my-storage-class
  azureFile:
    secretName: my-secret # ye secret ka naam diya hai apne man se
    shareName: pvc # ye share name diya hai jo file apni bani hui thi storage account ke andar uska nam
    # readOnly: false