apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
stringData:
  azurestorageaccountname: bambhole #ye storage accountka naam diya hai
  azurestorageaccountkey: ulFAXD9qZ3hG5W8zHXrUQjrGleVaF/B4u9pP7YolotliBXO8qgsVQO4wjWacp5eD1nbWEAsf2hRJ+AStEuw6aw==
  # ye storage accountka key diya hai
  # ye dono cheezein secret.yaml mein hai, jo ki pod.yaml aur pv.yaml mein use hoti hain